import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

String generateEmbeddedAssetsString(
  Directory buildDir, {
  required Map<String, String> inputHashes,
}) {
  final buffer = StringBuffer('''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/update_assets.dart

const assetInputs = <String, String>{
''');

  final sortedInputKeys = inputHashes.keys.toList()..sort();
  for (final key in sortedInputKeys) {
    final hash = inputHashes[key]!;
    buffer
      ..writeln("  '$key':")
      ..writeln("      '$hash',");
  }

  buffer.write('''
};

const embeddedAssets = <String, String>{
''');

  final files = buildDir.listSync().whereType<File>().toList()
    ..sort((a, b) => p.basename(a.path).compareTo(p.basename(b.path)));

  for (final file in files) {
    final basename = p.basename(file.path);
    if (_ignoredPatterns.any((p) => p.allMatches(basename).isNotEmpty)) {
      continue;
    }

    final bytes = file.readAsBytesSync();
    final compressedBytes = gzip.encode(bytes);
    final base64String = base64Encode(compressedBytes);

    buffer.writeln("  '$basename':");
    const chunkSize = 70;
    for (var i = 0; i < base64String.length; i += chunkSize) {
      final end = (i + chunkSize < base64String.length)
          ? i + chunkSize
          : base64String.length;
      final chunk = base64String.substring(i, end);
      final isLast = end == base64String.length;
      buffer.writeln("      '$chunk'${isLast ? ',' : ''}");
    }
  }

  buffer.writeln('};');
  return buffer.toString();
}

final Set<Pattern> _ignoredPatterns = {
  RegExp(r'^\.'),
  'packages',
  'viz_data.js',
  'web_app.dart2js.js.deps',
  'web_app.dart2js.js.info.json',
};

const _inputs = {'web', 'build.yaml', 'lib', 'pubspec.yaml'};

Future<Map<String, String>> hashInputs() async {
  final gitLs = await Process.run('git', ['ls-files', ..._inputs]);
  if (gitLs.exitCode != 0) {
    throw StateError('git ls-files failed');
  }

  final files =
      (gitLs.stdout as String).split('\n').where((s) => s.isNotEmpty).toList()
        ..sort();

  final regexes = _getLibSrcRegexes();

  final map = <String, String>{};
  for (final file in files) {
    if (file.startsWith('lib/assets/')) continue;
    if (file == 'web/viz_data.js') continue;

    if (file.startsWith('lib/src/')) {
      final matches = regexes.any((r) => r.hasMatch(file));
      if (!matches) continue;
    }

    final stream = File(file).openRead();
    final digest = await sha256.bind(stream).first;
    map[file] = digest.toString();
  }
  return map;
}

// TODO: consider just moving the "io" bits into a different directory
/// Parses `build.yaml` to extract the list of files under `lib/src/` that are
/// defined as sources for the default target.
///
/// Converts glob-style paths structure (e.g., `lib/src/opts.*`) into [RegExp]
/// formats suitable for exact path boundary validation.
List<RegExp> _getLibSrcRegexes() {
  final buildYamlString = File('build.yaml').readAsStringSync();
  final buildYaml = loadYaml(buildYamlString);

  if (buildYaml case {
    'targets': {r'$default': {'sources': final List<dynamic> sourcesList}},
  }) {
    final sources = sourcesList.cast<String>();

    return sources
        .where((s) => s.startsWith('lib/src/'))
        .map(
          (s) => RegExp('^${s.replaceAll('.', r'\.').replaceAll('*', '.*')}\$'),
        )
        .toList();
  }

  throw StateError('Could not parse sources from build.yaml');
}
